on: push
name: Slack Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: github
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
#          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Test
          SLACK_USERNAME: jnyakush
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}